server:
  servlet:
    context-path: /api

spring:
  data:
    cassandra:
      configFile: /cassandra/config/keyspaces-application.conf
      keyspaceName: boimama
      schema-action: NONE
  main:
    allow-bean-definition-overriding: true
  mvc:
    contentnegotiation:
      defaultContentType: application/json
  security:
    user:
      name: admin
      password: boimama
      roles: ADMIN

app:
  openapi:
    dev-url: http://localhost:8080/api
    prod-url: https://boimama-api.com/api

aws:
  region: eu-central-1
  data-bucket: boimama-data

# Reference: https://springdoc.org/#properties
springdoc:
  swagger-ui:
    path: /swagger.html  # swagger-ui custom path
