# This CI Workflow will build this boimama project with Github Actions
name: boimama.in CI Workflow

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build Backend (Springboot Application)
      run: |
        cd backend  
        # mvn clean install
        mvn package -DskipTests # Skip Unit Tests

    - name: Setup Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: boimama-app
        IMAGE_TAG: 0.0.1-SNAPSHOT
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG -f backend/Dockerfile backend
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag $IMAGE_NAME:$IMAGE_TAG 314201/$IMAGE_NAME:$IMAGE_TAG
        docker push 314201/$IMAGE_NAME:$IMAGE_TAG 

  frontend-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Upload frontend assets into AWS S3 bucket
      run: |
        cd frontend/user-portal
        chmod +x upload.sh  # Make the script executable
        ./upload.sh
